export {default as ContactPage} from './ContactPage'
export {default as WebPage} from './WebPage'
export {default as ContentPage} from './ContentPage'
export {default as NewsPage} from './NewsPage'
export {default as ServicePage} from './ServicePage'
export {default as ReviewServicePage} from './ReviewServicePage'
