export {default as ProfilePage} from './ProfilePage'
export {default as LoginPage} from './LoginPage'
export {default as WithdrawalHistoryPage} from './WithdrawalHistoryPage'
export {default as CodeVerificationPage} from './CodeVerificationPage'
export {default as NotificationPage} from './NotificationPage'
export {default as LoyaltyPage} from './LoyaltyPage'
export {default as SettingPage} from './SettingPage'
export {default as UserPage} from './UserPage'