export {default as ProfilePage} from './ProfilePage'
export {default as LoginPage} from './LoginPage'
export {default as WithdrawalHistoryPage} from './WithdrawalHistoryPage'
export {default as FriendPage} from './FriendPage'
export {default as NotificationPage} from './NotificationPage'
export {default as LoyaltyPage} from './LoyaltyPage'